#bardzo prosto wytłumaczone drzewo

In [1]:
import pandas as pd

In [63]:
dane = pd.read_csv('C:\Users\SC60VU\Desktop\klasyfikacja.csv', delimiter= ';'
                   ,names = ('NrKontraktu', 'TypKontraktu', 'TypUmowy', 'UzytkownikRejestracja'
                             , 'TypRoszczenia', 'MiesiaceOdRCD', 'StatusKomponentu'
                             , 'Wyplata', 'UzytkownikDecyzja', 'CzyClean', 'WiekUbez'
                             , 'PlecUbez', 'MarryUbez', 'VIP'))
dane = dane.drop(columns=['NrKontraktu','StatusKomponentu']) #usuwam kolumne
dl1 = len(dane) 
dane.dropna(inplace=True)
print('{0} (tj. {1:.0%}) obserwacji zostalo usuniętych z powodu braku danych').format(dl1-len(dane),(dl1-len(dane))*1.0/len(dane))

dane.head()

683 (tj. 5%) obserwacji zostalo usuniętych z powodu braku danych


TypKontraktu TypUmowy UzytkownikRejestracja          TypRoszczenia  \
0          TU1     TUL1                AM62KB                 ŚMIERĆ   
1          TU0     PD12                IV91BK     TRWAŁE INWALIDZTWO   
2          TU0     AB12                IV91BK  USZCZERBEK NA ZDROWIU   
3          TU0     HR12                PF35ZB       POBYT W SZPITALU   
6          TU0     HR12                AM62KB       POBYT W SZPITALU   

   MiesiaceOdRCD  Wyplata UzytkownikDecyzja  CzyClean  WiekUbez  PlecUbez  \
0           22.0        0            AM62KB         0      47.0         0   
1           41.0        1            IV91BK         1      40.0         1   
2           41.0        1            IV91BK         1      40.0         1   
3            9.0        1            PF35ZB         1       3.0         1   
6           31.0        0            AM62KB         1       6.0         0   

  MarryUbez  VIP  
0         Z    0  
1         Z    0  
2         Z    0  
3         S    0  
6         S    0

In [36]:
pd.get_dummies(dane['TypRoszczenia'], prefix='TypRoszczenia').head(1)

TypRoszczenia_CANCER  TypRoszczenia_MIESIĘCZNA WYPŁATA  \
0                     0                                 0   

   TypRoszczenia_OPERACJA  TypRoszczenia_POBYT W SZPITALU  \
0                       0                               0   

   TypRoszczenia_POWAŻNE ZACHOROWANIE  \
0                                   0   

   TypRoszczenia_PRZEJĘCIE OPŁACANIA SKŁADEK  TypRoszczenia_REKONWALESCENCJA  \
0                                          0                               0   

   TypRoszczenia_TRWAŁE INWALIDZTWO  TypRoszczenia_USZCZERBEK DZIECKA  \
0                                 0                                 0   

   TypRoszczenia_USZCZERBEK NA ZDROWIU  \
0                                    0   

   TypRoszczenia_ZAWARCIE ZWIĄZKU MAŁŻEŃSKIEGO  TypRoszczenia_ŚMIERĆ  
0                                            0                     1

In [71]:
from sklearn.model_selection import train_test_split
import numpy as np

In [64]:
dane = dane.join(pd.get_dummies(dane['TypRoszczenia'], prefix='TypRoszczenia'))
dane = dane.join(pd.get_dummies(dane['TypKontraktu'], prefix='TypKontraktu'))
dane = dane.join(pd.get_dummies(dane['TypUmowy'], prefix='TypUmowy'))
dane = dane.join(pd.get_dummies(dane['UzytkownikDecyzja'], prefix='UzytkownikDecyzja'))
dane = dane.join(pd.get_dummies(dane['MarryUbez'], prefix='MarryUbez'))
dane = dane.drop(columns = ['UzytkownikRejestracja','TypRoszczenia'
                     ,'TypUmowy','TypKontraktu','UzytkownikDecyzja','MarryUbez'])

In [65]:
Y = dane['Wyplata']
X = dane.drop(columns = ['Wyplata'])

In [66]:
X.head()

MiesiaceOdRCD  CzyClean  WiekUbez  PlecUbez  VIP  TypRoszczenia_CANCER  \
0           22.0         0      47.0         0    0                     0   
1           41.0         1      40.0         1    0                     0   
2           41.0         1      40.0         1    0                     0   
3            9.0         1       3.0         1    0                     0   
6           31.0         1       6.0         0    0                     0   

   TypRoszczenia_MIESIĘCZNA WYPŁATA  TypRoszczenia_OPERACJA  \
0                                 0                       0   
1                                 0                       0   
2                                 0                       0   
3                                 0                       0   
6                                 0                       0   

   TypRoszczenia_POBYT W SZPITALU  TypRoszczenia_POWAŻNE ZACHOROWANIE  ...  \
0                               0                                   0  ...   
1                               0                                   0  ...   
2                               0                                   0  ...   
3                               1                                   0  ...   
6                               1                                   0  ...   

   UzytkownikDecyzja_UF73LI  UzytkownikDecyzja_WL14FB  \
0                         0                         0   
1                         0                         0   
2                         0                         0   
3                         0                         0   
6                         0                         0   

   UzytkownikDecyzja_WR52HH  UzytkownikDecyzja_XF99FL  MarryUbez_   \
0                         0                         0            0   
1                         0                         0            0   
2                         0                         0            0   
3                         0                         0            0   
6                         0                         0            0   

   MarryUbez_N  MarryUbez_R  MarryUbez_S  MarryUbez_W  MarryUbez_Z  
0            0            0            0            0            1  
1            0            0            0            0            1  
2            0            0            0            0            1  
3            0            0            1            0            0  
6            0            0            1            0            0  

[5 rows x 213 columns]

In [67]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state=1)

In [57]:
from sklearn.tree import DecisionTreeClassifier

In [68]:
dt = DecisionTreeClassifier()
dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [75]:
from sklearn.metrics import classification_report, confusion_matrix

In [77]:
Y_pred = dt.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
#recall- czulosc
#precision- precyzja

[[ 664  535]
 [ 629 1589]]
              precision    recall  f1-score   support

           0       0.51      0.55      0.53      1199
           1       0.75      0.72      0.73      2218

   micro avg       0.66      0.66      0.66      3417
   macro avg       0.63      0.64      0.63      3417
weighted avg       0.67      0.66      0.66      3417



In [90]:
#Zwiększenie minimalnych wartości zdecydowanie poprawiło model
dt1 = DecisionTreeClassifier(min_samples_leaf= 15, criterion = 'gini', min_weight_fraction_leaf = 0.01)
dt1.fit(X_train, Y_train)
Y_pred = dt1.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 453  746]
 [ 236 1982]]
              precision    recall  f1-score   support

           0       0.66      0.38      0.48      1199
           1       0.73      0.89      0.80      2218

   micro avg       0.71      0.71      0.71      3417
   macro avg       0.69      0.64      0.64      3417
weighted avg       0.70      0.71      0.69      3417



In [95]:
dane_szpital = dane.loc[dane['TypRoszczenia_POBYT W SZPITALU']==1]
Y = dane_szpital['Wyplata']
X = dane_szpital.drop(columns = ['Wyplata'])
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state=1)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state=1)
dt2 = DecisionTreeClassifier()
dt2.fit(X_train, Y_train)
dt2 = DecisionTreeClassifier(min_samples_leaf= 15, criterion = 'gini', min_weight_fraction_leaf = 0.01)
dt2.fit(X_train, Y_train)
Y_pred = dt2.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[144 227]
 [121 528]]
              precision    recall  f1-score   support

           0       0.54      0.39      0.45       371
           1       0.70      0.81      0.75       649

   micro avg       0.66      0.66      0.66      1020
   macro avg       0.62      0.60      0.60      1020
weighted avg       0.64      0.66      0.64      1020

